### ISSUE TITLE
Model upload works partially 

### ISSUE THREAD

**Issue by yoav-b** [WQDSS/Evaluna#23]
Uploading a zip model adds it to the list of models to execute. But trying to run this added model fails.

**Comment by booooh** [comment]
Tested this by creating another zip file with the same contents as the default model, and naming it something else.
Uploaded the zip file (which doesn't contain a sub-directory, just the files), selected the model, and selected the test mock_input.json.

Execution proceeded as expected.

I think the problem is not with the upload, but with the fact that we're not reporting errors back.... I tried the same thing with the spokane model, and it failed without reporting why. Had to look at the logs to see that the model is missing the hangq01.csv file (the npt is there).

Can you confirm what is the case that you saw failing? Also can you dump the model-exec logs:
```
kubectl logs -n wq2dss -lapp.kubernetes.io/name=wq2dss-model-exec
```

**Comment by yoav-b** [comment]
The issue was that I compressed the folder and not directly the files... This should be covered in the documentation
